# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-03 07:35
from __future__ import unicode_literals

import ERP.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, null=True)),
                ('typ', models.CharField(choices=[('KeyNote', 'KeyNote'), ('Session', 'Session'), ('WorkSheet', 'WorkSheet'), ('Tea', 'Tea'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Network', 'Network')], max_length=20, null=True)),
                ('description', models.CharField(max_length=10000, null=True)),
                ('pic', models.ImageField(null=True, upload_to=ERP.models.getPicPath)),
                ('entryFee', models.FloatField(null=True)),
                ('moderator', models.CharField(max_length=200, null=True)),
                ('dayNumber', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('phoneNumber', models.CharField(max_length=14, null=True)),
                ('regId', models.CharField(max_length=20, null=True)),
                ('payAmount', models.FloatField(null=True)),
                ('payMode', models.CharField(max_length=20, null=True)),
                ('payDate', models.DateTimeField(null=True)),
                ('payRefference', models.CharField(max_length=50, null=True)),
                ('cancelReg', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('event_On', models.DateTimeField(null=True)),
                ('event_ends_On', models.DateTimeField(null=True)),
                ('regEndsOn', models.DateTimeField(null=True)),
                ('venue', models.CharField(max_length=200, null=True)),
                ('entryFee', models.FloatField(null=True)),
                ('description', models.CharField(max_length=30000, null=True)),
                ('venueGMapUrl', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
