# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-03 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0002_eventitem_eventregistration_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventitem',
            name='typ',
            field=models.CharField(choices=[('KeyNote', 'KeyNote'), ('Session', 'Session'), ('WorkShop', 'WorkShop'), ('Tea', 'Tea'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Network', 'Network')], max_length=20, null=True),
        ),
    ]
