# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-08 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0005_events_promoted'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
