# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-08 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0006_auto_20180508_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventitem',
            name='eventTime',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
