# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-08 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0007_eventitem_eventtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='ERP.Events'),
        ),
    ]
