# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-18 12:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0009_featuredpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredpage',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='featuredPageperson', to=settings.AUTH_USER_MODEL),
        ),
    ]
