# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-02 05:58
from __future__ import unicode_literals

import HR.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('key', models.CharField(max_length=200, null=True)),
                ('otp', models.PositiveIntegerField(null=True)),
                ('typ', models.CharField(choices=[(b'linklogin', b'linklogin'), (b'otp', b'otp')], max_length=20)),
                ('valid', models.BooleanField(default=False)),
                ('expiresOn', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('street', models.CharField(max_length=300, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('pincode', models.PositiveIntegerField(null=True)),
                ('country', models.CharField(default=b'India', max_length=50, null=True)),
                ('lat', models.CharField(max_length=15, null=True)),
                ('lon', models.CharField(max_length=15, null=True)),
                ('contactName', models.CharField(max_length=50, null=True)),
                ('contactNumber', models.CharField(max_length=14, null=True)),
                ('gstIn', models.CharField(max_length=10, null=True)),
                ('licenceNumber', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('displayPicture', models.ImageField(upload_to=HR.models.getDisplayPicturePath)),
                ('email', models.EmailField(max_length=50)),
                ('mobile', models.CharField(max_length=14, null=True)),
                ('website', models.URLField(blank=True, max_length=100, null=True)),
                ('cin', models.CharField(max_length=300, null=True)),
                ('year_established', models.CharField(max_length=300, null=True)),
                ('street', models.CharField(max_length=300, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('pincode', models.PositiveIntegerField(null=True)),
                ('country', models.CharField(default=b'India', max_length=50, null=True)),
                ('lat', models.CharField(max_length=15, null=True)),
                ('lon', models.CharField(max_length=15, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='office',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='HR.profile'),
        ),
    ]
