# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-02 06:25
from __future__ import unicode_literals

import HR.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='coverPicture',
            field=models.ImageField(null=True, upload_to=HR.models.getCoverPicturePath),
        ),
        migrations.AlterField(
            model_name='profile',
            name='displayPicture',
            field=models.ImageField(null=True, upload_to=HR.models.getDisplayPicturePath),
        ),
    ]
