# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-02 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
        ('HR', '0002_auto_20180502_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='office',
            old_name='branch',
            new_name='parent',
        ),
        migrations.AddField(
            model_name='office',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='buyingProduct',
            field=models.ManyToManyField(blank=True, related_name='productBuy', to='social.ProductTag'),
        ),
        migrations.AddField(
            model_name='profile',
            name='sellingProduct',
            field=models.ManyToManyField(blank=True, related_name='productSale', to='social.ProductTag'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
