# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-10 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0003_auto_20180502_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='messageAlert',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='newsletter',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='periodicNotification',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='promotional',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='requestAlert',
            field=models.BooleanField(default=True),
        ),
    ]
