# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-16 04:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HR', '0005_profile_fallowers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='fallowers',
        ),
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
