# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-03 05:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import social.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('typ', models.CharField(choices=[(b'Selling', b'Selling'), (b'Buying', b'Buying'), (b'Barter', b'Barter')], max_length=20, null=True)),
                ('txt', models.CharField(max_length=3000, null=True)),
                ('approved', models.BooleanField(default=True)),
                ('products', models.ManyToManyField(blank=True, related_name='productPost', to='social.ProductTag')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('txt', models.CharField(max_length=1000, null=True)),
                ('mention', models.ManyToManyField(blank=True, related_name='mentionedUser', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentedPost', to='social.Post')),
                ('replyTo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='social.PostComment')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postCommentUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likedPost', to='social.Post')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postLikeUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[(b'Image', b'Image'), (b'ImageLink', b'ImageLink'), (b'Video', b'Video'), (b'VideoLink', b'VideoLink')], max_length=20, null=True)),
                ('url', models.CharField(max_length=150, null=True)),
                ('fil', models.FileField(null=True, upload_to=social.models.getPostMediaAttachment)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mediaPost', to='social.Post')),
            ],
        ),
        migrations.CreateModel(
            name='PostResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('txt', models.CharField(max_length=1000, null=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ResponsePost', to='social.Post')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postResponseUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
