# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-16 04:06
from __future__ import unicode_literals

from django.db import migrations, models
import social.models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_auto_20180503_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='fil',
            field=models.FileField(null=True, upload_to=social.models.getPostCommentMediaAttachment),
        ),
    ]
