# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-17 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_auto_20180516_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlike',
            name='typ',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
