# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-17 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_postlike_typ'),
    ]

    operations = [
        migrations.AddField(
            model_name='postresponse',
            name='acknowledged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postresponse',
            name='status',
            field=models.CharField(choices=[(b'ignored', b'ignored'), (b'shortListed', b'shortListed'), (b'finalized', b'finalized')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='postresponse',
            name='typ',
            field=models.CharField(choices=[(b'Selling', b'Selling'), (b'Buying', b'Buying'), (b'Barter', b'Barter')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='postresponse',
            name='value',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
