# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-17 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import social.models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_auto_20180517_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='postresponse',
            name='fil',
            field=models.FileField(null=True, upload_to=social.models.getPostResponseMediaAttachment),
        ),
    ]
