# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-17 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_postresponse_fil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postresponse',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='social.Post'),
        ),
    ]
