# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-18 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_auto_20180517_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='postresponse',
            name='reply',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
